services:
  valkey:
    image: docker.io/bitnami/valkey:8.1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - .docker/valkey:/bitnami/valkey/data
